### ISSUE TITLE
Lost Image

### ISSUE THREAD

**Issue by Filmman586** [jneilliii/OctoPrint-UltimakerFormatPackage#47]
Been working fine, but yesterday I ran a print and the images don’t show up anymore. Latest version of octoprint, Cura and plug in installed.

**Comment by jneilliii** [comment]
are you running version 1.0.1? There was a bug in version 1.0.0 that caused the image to not update in the state panel. otherwise, I'll need a little more information as to how you are sending the file to octoprint, and errors in octoprint.log, or the browser's developer tools (F12) on the console tab.

**Comment by Filmman586** [comment]
UGH....Its working now! It didnt work yesterday and I ran a print 3 hours ago and it still wasn't there. I Just now sent it over to Octoprint and it's THERE!

I have attached the latest log file just in case you need it...

Lou
________________________________
