### ISSUE TITLE
Thumbnails missing after moving or renaming gcode

### ISSUE THREAD

**Issue by JanB97** [jneilliii/OctoPrint-UltimakerFormatPackage#59]
When I rename or move a file to a folder within the octoprint interface, my thumbnails just go away.
I tried the "Scan Files" button in the settings and now almost all of the thumbnails are gone, but without the broken image icon.

I am using Octoprint 1.8.1 with Version 1.0.2 of this plugin.

**Comment by jneilliii** [comment]
That's strange, during all my testing of moving files, the images would also be re-organized. Are there any errors in octoprint.log by chance around the time you moved the files? The scan files in the plugin doesn't work as well as it does with my Slicer Thumbnails plugin because the images aren't embedded in the gcode itself. I would personally recommend switching to that plugin as it supports all the major slicers used, including Cura. 

https://plugins.octoprint.org/plugins/prusaslicerthumbnails/

**Comment by JanB97** [comment]
No I don't see any errors unfortunately.
However, I have had similar errors in the past, but they where all just on single files and not all.
I will try the other plugin, thank you :)

**Comment by JanB97** [comment]
I am using the other plugin now, it does what I want, thank you!
