### ISSUE TITLE
State thumbnail only showing when it is not hidden

### ISSUE THREAD

**Issue by dekkerso** [jneilliii/OctoPrint-UltimakerFormatPackage#65]
When hiding the file which is printing, the thumbnail is not showing. This might be related to the bug where the thumbnail is not showing when in a different folder. Only showing in "state" when it is visible in "files"?

![image](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/assets/34577237/bfc838d5-42e1-4fb8-8c0c-b2da241dfb64)

![image](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/assets/34577237/0a83fdce-c9aa-453c-8f08-676e084a5c6e)

![image](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/assets/34577237/692f7b20-943c-4f05-a132-fe9aa58399fa)

**Comment by jneilliii** [comment]
So you start the print that was previously successful and then filter the file list to not show successful prints?

**Comment by dekkerso** [comment]
that filter is always on. when i reprint that print it will not show the thumbnail.
________________________________

**Comment by jneilliii** [comment]
I'm kind of not developing this plugin anymore because the [Slicer Thumbnails](https://plugins.octoprint.org/plugins/prusaslicerthumbnails/) plugin can handle multiple slicers and works for more people. I would recommend trying that one out, because I think I changed the logic in that plugin and it might not have this issue. Unfortunately, to switch you'll need to disable this plugin, install that one, make sure to restart Cura (possibly reconnect to OctoPrint in the printer settings) and enable the thumbnails post processing script in Cura. 

![image](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/assets/5249455/8b56b81a-e5bf-4bd3-92dc-3755934b9c89)

Once your files are re-uploaded and picked up by the Slicer Thumbnails plugin it should work pretty much the same as this one.
